<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxqcxzq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxqcxzq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxqcxzq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxqcxzq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxqcxzq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oxqcxzq',
    'container.build_id' => '7735b89c',
    'container.build_time' => 1689254156,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxqcxzq');
